<a href="https://colab.research.google.com/github/Hathan67/Hathan67/blob/main/hat_pandasdataanalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
hat = pd.read_csv("/content/drive/MyDrive/python/Superstore.csv")
#to write and store csv file use hat.to_csv('hathan.csv',index=false,columns =['columns to export'])
""" methods to write csv """
#skiprows=1 skips the 1st row also specify header=1
#header = none and names = column names removes and gives the column names
#nrows = n limits the rows the pd read
#na_values=[wrong values in the table] it haneges the values to NaN

' methods to write csv '

In [ ]:
hat

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
hat.shape

(9994, 21)

Change the type of Date Column

In [ ]:
hat['Order Date']=pd.to_datetime(hat['Order Date'])

In [ ]:
hat.info()

In [ ]:
hat.sort_values(['Order Date','Ship Date'],inplace=True,ascending=True)
hat.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
540,541,CA-2014-140795,2014-01-02,03-02-2014,First Class,BD-11500,Bradley Drucker,Consumer,United States,Green Bay,...,54302,Central,TEC-AC-10001432,Technology,Accessories,Enermax Aurora Lite Keyboard,468.900,6,0.0,206.3160
5713,5714,US-2014-143707,2014-01-03,05-03-2014,Standard Class,HR-14770,Hallie Redmond,Home Office,United States,New York City,...,10035,East,TEC-PH-10003655,Technology,Phones,Sannysis Cute Owl Design Soft Skin Case Cover ...,5.940,3,0.0,1.6038
6547,6548,CA-2014-113880,2014-01-03,05-03-2014,Standard Class,VF-21715,Vicky Freymann,Home Office,United States,Elmhurst,...,60126,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,634.116,6,0.3,-172.1172
6548,6549,CA-2014-113880,2014-01-03,05-03-2014,Standard Class,VF-21715,Vicky Freymann,Home Office,United States,Elmhurst,...,60126,Central,OFF-PA-10003036,Office Supplies,Paper,"Black Print Carbonless 8 1/2"" x 8 1/4"" Rapid M...",17.472,3,0.2,5.6784
7947,7948,CA-2014-131009,2014-01-03,05-03-2014,Standard Class,SC-20380,Shahid Collister,Consumer,United States,El Paso,...,79907,Central,OFF-FA-10004395,Office Supplies,Fasteners,Plymouth Boxed Rubber Bands by Plymouth,18.840,5,0.2,-3.5325
7948,7949,CA-2014-131009,2014-01-03,05-03-2014,Standard Class,SC-20380,Shahid Collister,Consumer,United States,El Paso,...,79907,Central,FUR-CH-10001270,Furniture,Chairs,Harbour Creations Steel Folding Chair,362.250,6,0.3,0.0000
7949,7950,CA-2014-131009,2014-01-03,05-03-2014,Standard Class,SC-20380,Shahid Collister,Consumer,United States,El Paso,...,79907,Central,FUR-FU-10001095,Furniture,Furnishings,DAX Black Cherry Wood-Tone Poster Frame,63.552,6,0.6,-34.9536
7950,7951,CA-2014-131009,2014-01-03,05-03-2014,Standard Class,SC-20380,Shahid Collister,Consumer,United States,El Paso,...,79907,Central,OFF-ST-10001469,Office Supplies,Storage,Fellowes Bankers Box Recycled Super Stor/Drawer,129.552,3,0.2,-22.6716
157,158,CA-2014-104269,2014-01-03,06-03-2014,Second Class,DB-13060,Dave Brooks,Consumer,United States,Seattle,...,98115,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.568,2,0.2,51.4764
8309,8310,CA-2014-168312,2014-01-03,07-03-2014,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Houston,...,77036,Central,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,137.352,3,0.2,8.5845

In [ ]:
hat.fillna(0,inplace = True)
""" cleaning data by removing null values called data wrangling or data munging """

' cleaning data by removing null values called data wrangling or data munging '

In [ ]:
#hat.fillna({key(columns):values})
#hat.ffill()
#hat.dropna()drops all olumns with na..dropna(how="all"),thersh=2 or 1 drop na rows only

In [ ]:
hat.desribe()
""" it gives the statistics of our DATA """

In [ ]:
hat.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

give products sold more than 5500

In [5]:
hat[["Product Name","Category","Customer Name"]][hat["Sales"]>5500]

,Product Name,Category,Customer Name
165,Lexmark MX611dhe Monochrome Laser Printer,Technology,Becky Martin
509,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,Christopher Martinez
683,Cubify CubeX 3D Printer Triple Head Print,Technology,Grant Thornton
2505,High Speed Automatic Electric Letter Opener,Office Supplies,Ken Lonsdale
2623,Canon imageCLASS 2200 Advanced Copier,Technology,Tom Ashbrook
2697,Cisco TelePresence System EX90 Videoconferenci...,Technology,Sean Miller
4098,Ibico EPK-21 Electric Binding System,Office Supplies,Sanjit Chand
4190,Canon imageCLASS 2200 Advanced Copier,Technology,Hunter Lopez
4277,"3D Systems Cube Printer, 2nd Generation, Magenta",Technology,Bill Shonely
6425,Canon imageCLASS 2200 Advanced Copier,Technology,Christopher Conant
6626,HP Designjet T520 Inkjet Large Format Printer ...,Technology,Tom Boeckenhauer
6826,Canon imageCLASS 2200 Advanced Copier,Technology,Tamara Chand
8153,Canon imageCLASS 2200 Advanced Copier,Technology,Raymond Buch
8488,HP Designjet T520 Inkjet Large Format Printer ...,Technology,Sanjit Engle
9039,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,Adrian Barton

In [ ]:
hat[['Order Date','Sales','Quantity']]

     Order Date    Sales  Quantity
540  2014-01-02  468.900         6
5713 2014-01-03    5.940         3
6547 2014-01-03  634.116         6
6548 2014-01-03   17.472         3
7947 2014-01-03   18.840         5
...         ...      ...       ...
908  2017-12-30   52.776         3
1296 2017-12-30   13.904         2
1297 2017-12-30   20.720         2
5091 2017-12-30    3.024         3
645  2017-12-30  209.300         2

[9994 rows x 3 columns]

In [ ]:
idx = pd.date_range('2014-01-01','2017-12-30')
hat.groupby('Order Date')[['Sales','Quantity']].sum().sort_values(['Order Date'],ascending=False).round(2).reindex(idx,fill_value=0)

              Sales  Quantity
2014-01-01     0.00         0
2014-01-02   468.90         6
2014-01-03  2203.15        40
2014-01-04   119.89        12
2014-01-05     0.00         0
...             ...       ...
2017-12-26   814.59        12
2017-12-27   177.64         6
2017-12-28  1657.35        64
2017-12-29  2915.53        41
2017-12-30   713.79        23

[1460 rows x 2 columns]

In [ ]:
# hat.sort_values(["Order Date"],ascending=True)

**Pivot** **Table**

In [28]:
hat.pivot_table(['Profit','Sales'],['Category'],aggfunc='mean')

                    Profit       Sales
Category
Furniture         8.699327  349.834887
Office Supplies  20.327050  119.324101
Technology       78.752002  452.709276